/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#e6f4ea',
        'tertiary-fixed-dim': '#a7f3d0',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#0f2417',
        'outline-variant': '#bbf7d0',
        'on-secondary-fixed-variant': '#14532d',
        'primary-fixed': '#bbf7d0',
        'secondary-fixed-dim': '#86efac',
        'on-error': '#ffffff',
        'tertiary-container': '#15803d',
        'secondary': '#166534',
        'on-primary-fixed': '#052e16',
        'on-tertiary-fixed': '#052e16',
        'primary': '#15803d',
        'surface-bright': '#f0fdf4',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#052e16',
        'on-secondary': '#ffffff',
        'on-primary-container': '#86efac',
        'outline': '#4ade80',
        'on-error-container': '#93000a',
        'surface-dim': '#dcfce7',
        'surface-variant': '#dcfce7',
        'on-background': '#052e16',
        'secondary-container': '#22c55e',
        'inverse-on-surface': '#ecfdf5',
        'tertiary': '#166534',
        'surface-tint': '#15803d',
        'on-surface': '#052e16',
        'primary-container': '#14532d',
        'surface-container-high': '#dcfce7',
        'primary-fixed-dim': '#86efac',
        'on-primary-fixed-variant': '#14532d',
        'background': '#f0fdf4',
        'surface-container-highest': '#d1fae5',
        'surface-container-low': '#f0fdf4',
        'on-surface-variant': '#166534',
        'on-secondary-container': '#052e16',
        'on-tertiary-container': '#bbf7d0',
        'on-tertiary-fixed-variant': '#14532d',
        'surface': '#f0fdf4',
        'secondary-fixed': '#dcfce7',
        'tertiary-fixed': '#dcfce7',
        'inverse-primary': '#86efac'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'stack-xl': '2rem',
        'stack-lg': '1.5rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'touch-target-min': '3rem',
        'stack-xs': '0.25rem',
        'card-padding': '1rem'
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
