/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#e6eeff',
        'tertiary-fixed-dim': '#b4c5ff',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#27313f',
        'outline-variant': '#c0c9be',
        'on-secondary-fixed-variant': '#6e3900',
        'primary-fixed': '#b1f2be',
        'secondary-fixed-dim': '#ffb77d',
        'on-error': '#ffffff',
        'tertiary-container': '#003fab',
        'secondary': '#904d00',
        'on-primary-fixed': '#00210d',
        'on-tertiary-fixed': '#00174b',
        'primary': '#003b1b',
        'surface-bright': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#2f1500',
        'on-secondary': '#ffffff',
        'on-primary-container': '#87c695',
        'outline': '#717970',
        'on-error-container': '#93000a',
        'surface-dim': '#d0dbed',
        'surface-variant': '#d9e3f6',
        'on-background': '#121c2a',
        'secondary-container': '#fe932c',
        'inverse-on-surface': '#eaf1ff',
        'tertiary': '#002b7b',
        'surface-tint': '#2e6a41',
        'on-surface': '#121c2a',
        'primary-container': '#14532d',
        'surface-container-high': '#dee9fc',
        'primary-fixed-dim': '#96d5a3',
        'on-primary-fixed-variant': '#12512c',
        'background': '#f8f9ff',
        'surface-container-highest': '#d9e3f6',
        'surface-container-low': '#eff4ff',
        'on-surface-variant': '#404941',
        'on-secondary-container': '#663500',
        'on-tertiary-container': '#9eb5ff',
        'on-tertiary-fixed-variant': '#003ea8',
        'surface': '#f8f9ff',
        'secondary-fixed': '#ffdcc3',
        'tertiary-fixed': '#dbe1ff',
        'inverse-primary': '#96d5a3'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'stack-xl': '2rem',
        'stack-lg': '1.5rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'touch-target-min': '3rem',
        'stack-xs': '0.25rem',
        'card-padding': '1rem'
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
